// ajax.js is intentionally empty
/*
     FILE ARCHIVED ON 07:52:16 Apr 03, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 20:44:04 Dec 02, 2017.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/